### PR TITLE
Consistent scss files convention

### PR DESCRIPTION
**Pull request by jadjoubran**
Consistent with the lectures
Avoids common confusion with the students not knowing why some of them are `.scss` and others are `.css.scss`

### CODE REVIEW

**Comment by ssaunier** [comment]
Hmm 🤔  Not sure about this one.

In Rails, we just go with `.scss` files now (cf https://github.com/lewagon/rails-stylesheets/)

**Comment by jadjoubran** [comment]
Okay then how about making it consistent the other way around?
Making all the files `.scss` (in this PR) and in the lecture?

**Comment by jadjoubran** [comment]
They normally get confused because some files are `.scss` and others are `.css.scss`

**Comment by jadjoubran** [comment]
@ssaunier should I send a new one with consistent `.scss` instead?

**Pull request closed without merging**
